## Arc
#bg0
background #2f343f
#fg
foreground #d3dae3
cursor #d3dae3
selection_foreground #d3dae3
#bg4
selection_background #525d76
#16 colors
#bg2 e bg4
color0  #404552
color8  #525d76
#red
color1  #e74c3c
color9  #e74c3c
#green
color2  #2ecc71
color10 #2ecc71
#yellow
color3  #f1c40f
color11 #f1c40f
#blue
color4  #5294e2
color12 #5294e2
#purple
color5  #9b59b6
color13 #9b59b6
#aqua
color6  #1abc9c
color14 #1abc9c
#white
color7  #d3dae3
color15 #ffffff
