## Bloody Night
#bg0
background #0a0a0a
#fg
foreground #d1d1d1
cursor #d1d1d1
selection_foreground #d1d1d1
#bg4
selection_background #2d2d2d
#16 colors
#bg2 e bg4
color0  #121212
color8  #2d2d2d
#red
color1  #bc0000
color9  #bc0000
#green
color2  #1b3022
color10 #1b3022
#yellow
color3  #6e4b00
color11 #6e4b00
#blue
color4  #1a2a3a
color12 #1a2a3a
#purple
color5  #3e1a3a
color13 #3e1a3a
#aqua
color6  #388e9d
color14 #388e9d
#white
color7  #d1d1d1
color15 #ffffff
