## Cyberpunk
#bg0
background #101116
#fg
foreground #f5f5f5
cursor #f5f5f5
selection_foreground #f5f5f5
#bg4
selection_background #323c58
#16 colors
#bg2 e bg4
color0  #212335
color8  #323c58
#red
color1  #ff0055
color9  #ff0055
#green
color2  #00b8ff
color10 #00b8ff
#yellow
color3  #d1ff00
color11 #d1ff00
#blue
color4  #00ff9f
color12 #00ff9f
#purple
color5  #ab00ff
color13 #ab00ff
#aqua
color6  #00f3ff
color14 #00f3ff
#white
color7  #f5f5f5
color15 #ffffff
