## Material Deep Ocean
#bg0
background #0f111a
#fg
foreground #a6accd
cursor #a6accd
selection_foreground #a6accd
#bg4
selection_background #4b5262
#16 colors
#bg2 e bg4
color0  #262a33
color8  #4b5262
#red
color1  #f07178
color9  #f07178
#green
color2  #c3e88d
color10 #c3e88d
#yellow
color3  #ffcb6b
color11 #ffcb6b
#blue
color4  #82aaff
color12 #82aaff
#purple
color5  #c792ea
color13 #c792ea
#aqua
color6  #89ddff
color14 #89ddff
#white
color7  #a6accd
color15 #ffffff
