## Dracula
#bg0
background #282a36
#fg
foreground #f8f8f2
cursor #f8f8f2
selection_foreground #f8f8f2
#bg4
selection_background #6272a4
#16 colors
#bg2 e bg4
color0  #414458
color8  #6272a4
#red
color1  #ff5555
color9  #ff5555
#green
color2  #50fa7b
color10 #50fa7b
#yellow
color3  #f1fa8c
color11 #f1fa8c
#blue
color4  #8be9fd
color12 #8be9fd
#purple
color5  #ff79c6
color13 #ff79c6
#aqua
color6  #9587f4
color14 #9587f4
#white
color7  #f8f8f2
color15 #ffffff
