## Ghost (Minimalist Desaturated)
#bg0
background #121212
#fg
foreground #cfcfcf
cursor #cfcfcf
selection_foreground #cfcfcf
#bg4
selection_background #404040
#16 colors
#bg2 e bg4
color0  #242424
color8  #404040
#red
color1  #8b0000
color9  #8b0000
#green
color2  #556b2f
color10 #556b2f
#yellow
color3  #8b8b83
color11 #8b8b83
#blue
color4  #708090
color12 #708090
#purple
color5  #483d8b
color13 #483d8b
#aqua
color6  #698b69
color14 #698b69
#white
color7  #cfcfcf
color15 #ffffff