## Horizon (Warm Dark High-Contrast)
#bg0
background #1c1e26
#fg
foreground #fdf0ed
cursor #fdf0ed
selection_foreground #fdf0ed
#bg4
selection_background #9ca1aa
#16 colors
#bg2 e bg4
color0  #2e303e
color8  #9ca1aa
#red
color1  #f43e5c
color9  #f43e5c
#green
color2  #09f7a0
color10 #09f7a0
#yellow
color3  #fac29a
color11 #fac29a
#blue
color4  #25b0bc
color12 #25b0bc
#purple
color5  #dfa0f0
color13 #dfa0f0
#aqua
color6  #21bfc2
color14 #21bfc2
#white
color7  #fdf0ed
color15 #ffffff
