## Kanagawa (Classic Japanese Art Tones)
#bg0
background #1f1f28
#fg
foreground #dcd7ba
cursor #dcd7ba
selection_foreground #dcd7ba
#bg4
selection_background #54546d
#16 colors
#bg2 e bg4
color0  #22222a
color8  #54546d
#red
color1  #c34043
color9  #c34043
#green
color2  #76946a
color10 #76946a
#yellow
color3  #dca561
color11 #dca561
#blue
color4  #7e9cd8
color12 #7e9cd8
#purple
color5  #957fb8
color13 #957fb8
#aqua
color6  #7aa89f
color14 #7aa89f
#white
color7  #dcd7ba
color15 #ffffff

