## Monokai Pro (The Classic Dev Look)
#bg0
background #2d2a2e
#fg
foreground #fcfcfa
cursor #fcfcfa
selection_foreground #fcfcfa
#bg4
selection_background #727072
#16 colors
#bg2 e bg4
color0  #403e41
color8  #727072
#red
color1  #ff6188
color9  #ff6188
#green
color2  #a9dc76
color10 #a9dc76
#yellow
color3  #ffd866
color11 #ffd866
#blue
color4  #78dce8
color12 #78dce8
#purple
color5  #d670d6
color13 #d670d6
#aqua
color6  #ab9df2
color14 #ab9df2
#white
color7  #fcfcfa
color15 #ffffff

