## Nord
#bg0
background #2e3440
#fg
foreground #eceff4
cursor #eceff4
selection_foreground #eceff4
#bg4
selection_background #616e88
#16 colors
#bg2 e bg4
color0  #434c5e
color8  #616e88
#red
color1  #bf616a
color9  #bf616a
#green
color2  #a3be8c
color10 #a3be8c
#yellow
color3  #ebcb8b
color11 #ebcb8b
#blue
color4  #81a1c1
color12 #81a1c1
#purple
color5  #b48ead
color13 #b48ead
#aqua
color6  #88c0d0
color14 #88c0d0
#white
color7  #eceff4
color15 #ffffff

