## Oxocarbon (Cold & Tech)
#bg0
background #161616
#fg
foreground #f2f4f8
cursor #f2f4f8
selection_foreground #f2f4f8
#bg4
selection_background #dde1e6
#16 colors
#bg2 e bg4
color0  #393939
color8  #dde1e6
#red
color1  #fa4d56
color9  #fa4d56
#green
color2  #42be65
color10 #42be65
#yellow
color3  #ee5396
color11 #ee5396
#blue
color4  #08bdba
color12 #08bdba
#purple
color5  #be95ff
color13 #be95ff
#aqua
color6  #33b1ff
color14 #33b1ff
#white
color7  #f2f4f8
color15 #ffffff
