## Rose Pine (Elegant & Muted)
#bg0
background #191724
#fg
foreground #e0def4
cursor #e0def4
selection_foreground #e0def4
#bg4
selection_background #524f67
#16 colors
#bg2 e bg4
color0  #26233a
color8  #524f67
#red
color1  #eb6f92
color9  #eb6f92
#green
color2  #9ccfd8
color10 #9ccfd8
#yellow
color3  #ebbcba
color11 #ebbcba
#blue
color4  #31748f
color12 #31748f
#purple
color5  #c4a7e7
color13 #c4a7e7
#aqua
color6  #eb6f92
color14 #eb6f92
#white
color7  #e0def4
color15 #ffffff

