## Tokyo Night
#bg0
background #1a1b26
#fg
foreground #c0caf5
cursor #c0caf5
selection_foreground #c0caf5
#bg4
selection_background #565f89
#16 colors
#bg2 e bg4
color0  #2f3549
color8  #565f89
#red
color1  #f7768e
color9  #f7768e
#green
color2  #9ece6a
color10 #9ece6a
#yellow
color3  #e0af68
color11 #e0af68
#blue
color4  #7aa2f7
color12 #7aa2f7
#purple
color5  #bb9af7
color13 #bb9af7
#aqua
color6  #7dcfff
color14 #7dcfff
#white
color7  #c0caf5
color15 #ffffff


