#######################
#######################
#######################

#don't jurge me, this is gemini's shit, i just wanted something that works

source = hyprland/colors/colors.conf

general{
    no_fade_in = false
    grace = 1
    disable_loading = true
    ignore_empty_input = true
}

background{
    monitor =
    path = screenshot
    color = $bg0
    blur_enabled = true
    blur_size = 5         
    blur_passes = 3       
    noise = 0.0117      
    contrast = 1 
    brightness = 0.6
    vibrancy = 0.2
    vibrancy_darkness = 0.1
}


label{
    monitor =
    text = cmd[update:1000] echo "$(date +%H)"
    color = $blue
    font_size = 100
    font_family = JetBrainsMono Nerd Font Propo Bold
    position = 0, 210
    halign = center
    valign = center
}

label{
    monitor =
    text = cmd[update:10] echo "$(date +%M)"
    color = $blue
    font_size = 100
    font_family = JetBrainsMono Nerd Font Propo Bold
    position = 0, 80
    halign = center
    valign = center
}

label{
    monitor =
    text = cmd[update:1000] echo "$(date +%A)"
    color = $blue
    font_size = 30
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, -10
    halign = center
    valign = center
}

label{
    monitor =
    text = cmd[update:1000] echo "$(date +%d\ %b)"
    color = $blue
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 0, -50
    halign = center
    valign = center
}

label{
    monitor =
    text = $USER
    color = $blue
    font_size = 32
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, -120
    halign = center
    valign = center
}

input-field{
    monitor =
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = $bg2 $bg4 $bg2 $bg4 25deg
    inner_color = rgba(0, 0, 0, 0.19)
    font_color = $fg
    fade_on_empty = true
    hide_input = false
    placeholder_text =
    check_color = $bg4 $blue $bg4 $blue 25deg
    fail_text =
    fail_text_color = $red
    fail_color = $bg4 $red $bg4 $red 45deg
    position = 0, -200
    halign = center
    valign = center
}

animations{
    enabled = true
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear 
    animation = inputFielWidth, 1, 2, linear 
    bezier = linear, 1, 1, 0, 0
}

# shape{
#     monitor =
#     size = 180, 45
#     color = $fg
#     rounding = 12
#     border_size = 1
#     border_color = $bg2
#     position = -30, -30
#     halign = right
#     valign = top
# }

# label{
#     monitor =
#     text = cmd[update: 100] ~/.config/hypr/lock-kb.sh && echo "Keyboard On"
#     color = $blue
#     font_size = 12
#     font_family = JetBrainsMono Nerd Font Bold
#     position = 0, -120
#     halign = right
#     valign = top
# }

