## Arc
$bg0 = rgb(2f343f)
$bg1 = rgb(383c4a)
$bg2 = rgb(404552)
$bg3 = rgb(4b5162)
$bg4 = rgb(525d76)
$blue = rgb(5294e2)
$orange = rgb(e67e22)
$yellow = rgb(f1c40f)
$green = rgb(2ecc71)
$aqua = rgb(1abc9c)
$red = rgb(e74c3c)
$purple = rgb(9b59b6)
$grey0 = rgba(565f73ee)
$grey1 = rgba(676f83ee)
$grey2 = rgba(7c818cee)
$fg = rgb(d3dae3)
