## Cyberpunk
$bg0 = rgb(101116)
$bg1 = rgb(151921)
$bg2 = rgb(212335)
$bg3 = rgb(2d3345)
$bg4 = rgb(323c58)
$blue = rgb(00ff9f)
$orange = rgb(f6eb61)
$yellow = rgb(d1ff00)
$green = rgb(00b8ff)
$aqua = rgb(00f3ff)
$red = rgb(ff0055)
$purple = rgb(ab00ff)
$grey0 = rgba(393d56ee)
$grey1 = rgba(444b6aee)
$grey2 = rgba(636da6ee)
$fg = rgb(f5f5f5)
