## Material Deep Ocean
$bg0 = rgb(0f111a)
$bg1 = rgb(1a1c25)
$bg2 = rgb(262a33)
$bg3 = rgb(353a45)
$bg4 = rgb(4b5262)
$blue = rgb(82aaff)
$orange = rgb(f78c6c)
$yellow = rgb(ffcb6b)
$green = rgb(c3e88d)
$aqua = rgb(89ddff)
$red = rgb(f07178)
$purple = rgb(c792ea)
$grey0 = rgba(546e7aee)
$grey1 = rgba(607d8bee)
$grey2 = rgba(90a4aeee)
$fg = rgb(a6accd)
