## Dracula
$bg0 = rgb(282a36)
$bg1 = rgb(343746)
$bg2 = rgb(414458)
$bg3 = rgb(44475a)
$bg4 = rgb(6272a4)
$blue = rgb(8be9fd)
$orange = rgb(ffb86c)
$yellow = rgb(f1fa8c)
$green = rgb(50fa7b)
$aqua = rgb(9587f4)
$red = rgb(ff5555)
$purple = rgb(ff79c6)
$grey0 = rgba(44475aee)
$grey1 = rgba(6272a4ee)
$grey2 = rgba(94aef2ee)
$fg = rgb(f8f8f2)
