## Ghost (Minimalist Desaturated)
$bg0 = rgb(121212)
$bg1 = rgb(181818)
$bg2 = rgb(242424)
$bg3 = rgb(303030)
$bg4 = rgb(404040)
$blue = rgb(708090)
$orange = rgb(a0522d)
$yellow = rgb(8b8b83)
$green = rgb(556b2f)
$aqua = rgb(698b69)
$red = rgb(8b0000)
$purple = rgb(483d8b)
$grey0 = rgba(404040ee)
$grey1 = rgba(606060ee)
$grey2 = rgba(a0a0a0ee)
$fg = rgb(cfcfcf)