## Horizon (Warm Dark High-Contrast)
$bg0 = rgb(1c1e26)
$bg1 = rgb(232530)
$bg2 = rgb(2e303e)
$bg3 = rgb(6f6f70)
$bg4 = rgb(9ca1aa)
$blue = rgb(25b0bc)
$orange = rgb(e95678)
$yellow = rgb(fac29a)
$green = rgb(09f7a0)
$aqua = rgb(21bfc2)
$red = rgb(f43e5c)
$purple = rgb(dfa0f0)
$grey0 = rgba(6f6f70ee)
$grey1 = rgba(9ca1aaee)
$grey2 = rgba(d5d8daee)
$fg = rgb(fdf0ed)
