## Kanagawa (Classic Japanese Art Tones)
$bg0 = rgb(1f1f28)
$bg1 = rgb(16161d)
$bg2 = rgb(22222a)
$bg3 = rgb(363646)
$bg4 = rgb(54546d)
$blue = rgb(7e9cd8)
$orange = rgb(ffa066)
$yellow = rgb(dca561)
$green = rgb(76946a)
$aqua = rgb(7aa89f)
$red = rgb(c34043)
$purple = rgb(957fb8)
$grey0 = rgba(727169ee)
$grey1 = rgba(a6a69dee)
$grey2 = rgba(dcd7baee)
$fg = rgb(dcd7ba)

