## Midnight (Pure Amoled Black)
$bg0 = rgb(000000)
$bg1 = rgb(080808)
$bg2 = rgb(121212)
$bg3 = rgb(1c1c1c)
$bg4 = rgb(262626)
$blue = rgb(0077ff)
$orange = rgb(ff8800)
$yellow = rgb(ffee00)
$green = rgb(00ff88)
$aqua = rgb(00ffff)
$red = rgb(ff0044)
$purple = rgb(aa00ff)
$grey0 = rgba(333333ee)
$grey1 = rgba(444444ee)
$grey2 = rgba(666666ee)
$fg = rgb(eeeeee)
