## Monokai Pro (The Classic Dev Look)
$bg0 = rgb(2d2a2e)
$bg1 = rgb(221f22)
$bg2 = rgb(403e41)
$bg3 = rgb(5b595c)
$bg4 = rgb(727072)
$blue = rgb(78dce8)
$orange = rgb(fc9867)
$yellow = rgb(ffd866)
$green = rgb(a9dc76)
$aqua = rgb(ab9df2)
$red = rgb(ff6188)
$purple = rgb(d670d6)
$grey0 = rgba(5b595cee)
$grey1 = rgba(727072ee)
$grey2 = rgba(939293ee)
$fg = rgb(fcfcfa)

