## Oceanic Next (Deep Sea Focus)
$bg0 = rgb(1b2b34)
$bg1 = rgb(343d46)
$bg2 = rgb(4f5b66)
$bg3 = rgb(65737e)
$bg4 = rgb(a7adba)
$blue = rgb(6699cc)
$orange = rgb(f99157)
$yellow = rgb(fac863)
$green = rgb(99c794)
$aqua = rgb(5fb3b3)
$red = rgb(ec5f67)
$purple = rgb(c594c5)
$grey0 = rgba(65737eee)
$grey1 = rgba(a7adbaee)
$grey2 = rgba(c0c5ceee)
$fg = rgb(d8dee9)

