$bg0 =       rgb(282c34)
$bg1 =       rgb(21252b)
$bg2 =       rgb(2c313a)
$bg3 =       rgb(3e4451)
$bg4 =       rgb(4b5263)

$fg =        rgb(abb2bf)

$red =       rgb(e08c75)
$orange =    rgb(d19a66)
$yellow =    rgb(e5c07b)
$green =     rgb(98c379)
$aqua =      rgb(56b6c2)
$blue =      rgb(61afef)
$purple =    rgb(c678dd)

$grey0 =     rgba(5c6370aa)
$grey1 =     rgba(828997aa)
$grey2 =     rgba(abb2bfaa)
