## Oxocarbon (Cold & Tech)
$bg0 = rgb(161616)
$bg1 = rgb(262626)
$bg2 = rgb(393939)
$bg3 = rgb(525252)
$bg4 = rgb(dde1e6)
$blue = rgb(08bdba)
$orange = rgb(ff7eb6)
$yellow = rgb(ee5396)
$green = rgb(42be65)
$aqua = rgb(33b1ff)
$red = rgb(fa4d56)
$purple = rgb(be95ff)
$grey0 = rgba(525252ee)
$grey1 = rgba(dde1e6ee)
$grey2 = rgba(ffffffee)
$fg = rgb(f2f4f8)
