## Rose Pine (Elegant & Muted)
$bg0 = rgb(191724)
$bg1 = rgb(1f1d2e)
$bg2 = rgb(26233a)
$bg3 = rgb(403d52)
$bg4 = rgb(524f67)
$blue = rgb(31748f)
$orange = rgb(f6c177)
$yellow = rgb(ebbcba)
$green = rgb(9ccfd8)
$aqua = rgb(eb6f92)
$red = rgb(eb6f92)
$purple = rgb(c4a7e7)
$grey0 = rgba(6e6a86ee)
$grey1 = rgba(908caaee)
$grey2 = rgba(e0def4ee)
$fg = rgb(e0def4)

