## Solarized Dark (Balanced & Academic)
$bg0 = rgb(002b36)
$bg1 = rgb(073642)
$bg2 = rgb(586e75)
$bg3 = rgb(657b83)
$bg4 = rgb(839496)
$blue = rgb(268bd2)
$orange = rgb(cb4b16)
$yellow = rgb(b58900)
$green = rgb(859900)
$aqua = rgb(2aa198)
$red = rgb(dc322f)
$purple = rgb(d33682)
$grey0 = rgba(586e75ee)
$grey1 = rgba(93a1a1ee)
$grey2 = rgba(eee8d5ee)
$fg = rgb(839496)

