## Tokyo Night
$bg0 = rgb(1a1b26)
$bg1 = rgb(24283b)
$bg2 = rgb(2f3549)
$bg3 = rgb(414868)
$bg4 = rgb(565f89)
$blue = rgb(7aa2f7)
$orange = rgb(ff9e64)
$yellow = rgb(e0af68)
$green = rgb(9ece6a)
$aqua = rgb(7dcfff)
$red = rgb(f7768e)
$purple = rgb(bb9af7)
$grey0 = rgba(414868ee)
$grey1 = rgba(565f89ee)
$grey2 = rgba(a9b1d6ee)
$fg = rgb(c0caf5)


